E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Categories/List.cshtml.cs
using E_Learning_Course.Data.Entities;
using E_Learning_Course.WebApp.ContextFactory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using X.PagedList.Extensions;

namespace E_Learning_Course.WebApp.Pages.Admin.Categories
{
    [Authorize(Roles = "Administrator")]
    public class ListModel : PageModel
    {
        public List<Category> Categories { get; set; }

        public IPagedList<Category> PagedCategories { get; set; }

        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }
        public int? PageSize { get; set; }
        public int? PageNo { get; set; }

        public int? TotalPage { get; set; }
        public IActionResult OnGet(int? pageNo, int? pageSize, string? searchTxt, string? sortBy)
        {
            if (pageNo == null)
            {
                pageNo = 1;
            }
            if (pageSize == null)
            {
                pageSize = 5;
            }
            if (searchTxt != null)
            {
                CurrentFilter = searchTxt;
            }
            PageNo = pageNo;
            PageSize = pageSize;

            using (var context = new RespositoryContextFactory().CreateDbContext(null))
            {
                IQueryable<Category> query = context.Categories;
                if (!string.IsNullOrEmpty(searchTxt))
                {
                    query = query.Where(x => (x.Name + x.Description).Contains(searchTxt));
                }
                // S?p x?p
                if (!string.IsNullOrEmpty(sortBy))
                {
                    //var sort = (sortBy != null) ? CurrentSort : sortBy;

                    CurrentSort = sortBy;
                    var sortParams = sortBy.Split('|');
                    string sortField = sortParams[0];
                    string sortDirection = sortParams[1];

                    query = sortField switch
                    {
                        "name" => sortDirection == "asc" ? query.OrderBy(c => c.Name) : query.OrderByDescending(c => c.Name),
                        _ => query
                    };
                }
                PagedCategories = query.ToPagedList((int)pageNo, (int)pageSize);
                List<Category> listCate = query.ToList();
                int morePage = (listCate.Count % pageSize != 0 ? 1 : 0);
                TotalPage = (int)(listCate.Count / pageSize) + morePage;
            }
            return Page();
        }

    }

}

E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Comments/List.cshtml.cs
using E_Learning_Course.Data;
using E_Learning_Course.Data.Entities;
using E_Learning_Course.Service;
using E_Learning_Course.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Net.NetworkInformation;
using X.PagedList;
using X.PagedList.Extensions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace E_Learning_Course.WebApp.Pages.Admin.Comments
{
    [Authorize(Roles = "Administrator, Instructor")]
    public class ListModel : PageModel
    {
        private readonly ICommentService _commentService;
        private readonly RepositoryContext _context;

        public ListModel(ICommentService commentService, RepositoryContext context)
        {
            _commentService = commentService;
            _context = context;
        }


        [BindProperty]
        public int LessonId { get; set; }

        [BindProperty]
        public string CommentContent { get; set; }

        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public int CourseId { get; set; }

        [BindProperty]
        public string EditedCommentContent { get; set; }

        public List<CommentList> Comments { get; set; }

        public IPagedList<CommentList> PagedComment { get; set; }

        public string CurrentFilter { get; set; } = "";
        public string CurrentSort { get; set; }
        public int? PageSize { get; set; }
        public int? PageNo { get; set; }

        public int? TotalPage { get; set; }

        public async Task OnGetAsync(int lessonId, int? pageNo, int? pageSize, DateTime? fromDate, DateTime? toDate, string content = null, string userId = null, bool? isDeleted = null)
        {
            
            LessonId = lessonId;
            pageNo ??= 1;
            pageSize ??= 5;

            var commentQuery = await _commentService.SearchCommentsAsync(
                content,
                userId,
                isDeleted,
                fromDate,
                toDate
            );

            PagedComment = commentQuery.ToPagedList((int)pageNo, (int)pageSize);

            int totalItems = commentQuery.Count();
            int morePage = totalItems % pageSize != 0 ? 1 : 0;
            TotalPage = ( totalItems / pageSize ) + morePage;

            PageNo = pageNo;
            PageSize = pageSize;

        }

        public async Task<IActionResult> OnPostAddReplyCommentAsync(CommentList newComment , int lessonId)
        {

            var lessonExists = await _context.Lessons.AnyAsync (l => l.Id == lessonId);
            if ( string.IsNullOrWhiteSpace (CommentContent) ) {
                ModelState.AddModelError ("CommentContent", "Bình luận không được để trống.");
                return Page ();
            }

            //var cleanContent = ProcessedCommentContent (CommentContent);

            var commentForCreation = new CommentForCreation
            {
                LessonId = lessonId,
                ParentCommentId = newComment.ParentCommentId,
                Content = CommentContent
            };

            await _commentService.AddCommentAsync (commentForCreation);
            Comments = await _commentService.GetCommentsByLessonIdAsync(lessonId);

            return RedirectToPage ("/Admin/Comments/List");
        }

        public async Task<IActionResult> OnPostEditCommentAsync(int Id, string EditedCommentContent, int lessonId)
        {
            var success = await _commentService.EditCommentAsync (Id, EditedCommentContent);
            if ( !success ) {
                ModelState.AddModelError ("EditedCommentContent", "Không thể chỉnh sửa bình luận hoặc bình luận không tồn tại.");
                return Page ();
            }

            if ( string.IsNullOrWhiteSpace (EditedCommentContent) ) {
                ModelState.AddModelError ("EditedCommentContent", "Nội dung bình luận không được để trống.");
                return Page ();
            }

            return RedirectToPage ("/Admin/Comments/List");

        }

        public async Task<IActionResult> OnPostDeleteCommentAsync(int Id)
        {
            var success = await _commentService.DeleteCommentAsync (Id);

            if ( !success ) {
                ModelState.AddModelError ("DeleteComment", "Không thể xóa bình luận.");
            }

            // Sau khi xóa, chuyển hướng lại trang học
            return RedirectToPage ("/Admin/Comments/List");
        }
    }
}

E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Courses/List.cshtml.cs
using E_Learning_Course.Data;
using E_Learning_Course.Data.Entities;
using E_Learning_Course.WebApp.ContextFactory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using X.PagedList;
using X.PagedList.Extensions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
namespace E_Learning_Course.WebApp.Pages.Admin.Courses
{
    [Authorize(Roles = "Administrator, Instructor")]
    public class ListModel : PageModel
    {
        public List<Category> Categories { get; set; }
        public List<Course> Courses { get; set; }
        private readonly RepositoryContext _context;
        public IPagedList<Course> PagedCourses { get; set; }
        public string CurrentFilter { get; set; } = "";
        public string CurrentSort { get; set; }
        public int? PageSize { get; set; }
        public int? PageNo { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? CategoryId { get; set; }
        public int? TotalPage { get; set; }
        public ListModel(RepositoryContext context)
        {
            _context = context;
        }
        public IActionResult OnGet(int? pageNo, int? pageSize, string? searchTxt, string? sortBy)
        {
            Categories =  _context.Categories.ToList();
            if (pageNo == null)
            {
                pageNo = 1;
            }
            if (pageSize == null)
            {
                pageSize = 5;
            }
            if (searchTxt != null)
            {
                CurrentFilter = searchTxt;
            }
            PageNo = pageNo;
            PageSize = pageSize;

            using (var context = new RespositoryContextFactory().CreateDbContext(null))
            {
                IQueryable<Course> query = context.Courses.Include(x => x.Category).OrderByDescending(c=>c.CreatedAt);
                if(User.IsInRole("Instructor"))
                {
                    query = query.Where(x => x.CreateBy == User.FindFirstValue(ClaimTypes.NameIdentifier));
                }    
                if (!string.IsNullOrEmpty(searchTxt))
                {
                    query = query.Where(x => (x.Title + x.Status + x.Category.Name).Contains(searchTxt));
                }
                if (CategoryId.HasValue)
                {
                    query = query.Where(c => c.CategoryId == CategoryId.Value);
                }

                // Sắp xếp
                if (!string.IsNullOrEmpty(sortBy))
                {
                    //var sort = (sortBy != null) ? CurrentSort : sortBy;

                    CurrentSort = sortBy;
                    var sortParams = sortBy.Split('|');
                    string sortField = sortParams[0];
                    string sortDirection = sortParams[1];

                    query = sortField switch
                    {
                        "name" => sortDirection == "asc" ? query.OrderBy(c => c.Title) : query.OrderByDescending(c => c.Title),
                        "price" => sortDirection == "asc" ? query.OrderBy(c => c.Price) : query.OrderByDescending(c => c.Price),
                        //"view" => sortDirection == "asc" ? query.OrderBy(c => c.ViewCount) : query.OrderByDescending(c => c.ViewCount),
                        "date" => sortDirection == "asc" ? query.OrderBy(c => c.CreatedAt) : query.OrderByDescending(c => c.CreatedAt),
                        _ => query
                    };
                }
                PagedCourses = query.ToPagedList((int)pageNo, (int)pageSize);
                List<Course> listCourse = query.ToList();
                int morePage = listCourse.Count % pageSize != 0 ? 1 : 0;
                TotalPage = (int)(listCourse.Count / pageSize) + morePage;
            }
            return Page();
        }
    }
}

E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Discounts/List.cshtml.cs
using E_Learning_Course.Data.Entities;
using E_Learning_Course.WebApp.ContextFactory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using X.PagedList.Extensions;

namespace E_Learning_Course.WebApp.Pages.Admin.Discounts
{
    [Authorize(Roles = "Administrator, Instructor")]
    public class ListModel : PageModel
    {
        public List<Discount> Discounts { get; set; }
        public IPagedList<Discount> PagedDiscount { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }
        public int? PageSize { get; set; }
        public int? PageNo { get; set; }

        public int? TotalPage { get; set; }
        public IActionResult OnGet(int? pageNo, int? pageSize, string? searchTxt, string? sortBy)
        {
            if (pageNo == null)
            {
                pageNo = 1;
            }
            if (pageSize == null)
            {
                pageSize = 1;
            }
            if (searchTxt != null)
            {
                CurrentFilter = searchTxt;
            }
            PageNo = pageNo;
            PageSize = pageSize;

            using (var context = new RespositoryContextFactory().CreateDbContext(null))
            {
                IQueryable<Discount> query = context.Discounts;
                if (!string.IsNullOrEmpty(searchTxt))
                {
                    query = query.Where(x => (x.Code).Contains(searchTxt));
                }
                // S?p x?p

                if (!string.IsNullOrEmpty(sortBy))
                {
                    //var sort = (sortBy != null) ? CurrentSort : sortBy;

                    CurrentSort = sortBy;
                    var sortParams = sortBy.Split('|');
                    string sortField = sortParams[0];
                    string sortDirection = sortParams[1];

                    query = sortField switch
                    {
                        "name" => sortDirection == "asc" ? query.OrderBy(c => c.Code) : query.OrderByDescending(c => c.Code),
                        "date" => sortDirection == "asc" ? query.OrderBy(c => c.CreatedAt) : query.OrderByDescending(c => c.CreatedAt),
                        _ => query
                    };
                }


                PagedDiscount = query.ToPagedList((int)pageNo, (int)pageSize);
                List<Discount> listDiscount = query.ToList();
                int morePage = (listDiscount.Count % pageSize != 0 ? 1 : 0);
                TotalPage = (int)(listDiscount.Count / pageSize) + morePage;

            }
            return Page();
        }
    }
}

E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Payments/List.cshtml.cs
using E_Learning_Course.Service;
using E_Learning_Course.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using X.PagedList;
using X.PagedList.Extensions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace E_Learning_Course.WebApp.Pages.Admin.Payments
{
    [Authorize(Roles = "Administrator")]
    public class ListModel : PageModel
    {
        private readonly IPaymentService _paymentService;

        public ListModel(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }

        public List<PaymentList> Payments { get; set; }


        public IPagedList<PaymentList> PagedPayments { get; set; }

        public string CurrentFilter { get; set; } = "";
        public string CurrentSort { get; set; }
        public int? PageSize { get; set; }
        public int? PageNo { get; set; }

        public int? TotalPage { get; set; }


        public async Task OnGetAsync(DateTime? fromDate, DateTime? toDate, string orderNumber, int? status, int? pageNo, int? pageSize)
        {
            pageNo ??= 1;
            pageSize ??= 5;

            var paymentsQuery = await _paymentService.SearchPaymentsAsync (fromDate, toDate, orderNumber, status);

            PagedPayments = paymentsQuery.ToPagedList ((int)pageNo, (int)pageSize);

            int totalItems = paymentsQuery.Count ();
            int morePage = totalItems % pageSize != 0 ? 1 : 0;
            TotalPage = ( totalItems / pageSize ) + morePage;

            PageNo = pageNo;
            PageSize = pageSize;
        }

    }
}

E-Learning-Course/E-Learning-Course/E-Learning-Course.WebApp/Pages/Admin/Comments/List.cshtml
@page
@model E_Learning_Course.WebApp.Pages.Admin.Comments.ListModel
@{
    Layout = "_ManagementLayout";
}


<style>
    body {
        font-family: Arial, sans-serif;
        font-size: 14px;
        color: #444;
    }

    .table-header {
        font-weight: bold;
        color: #555;
        font-size: 12px;
        padding: 8px;
        background-color: #e9ecef;
        border: 1px solid #ddd;
    }

    .comment-row:hover {
        background-color: #fff7e6;
        transition: background-color 0.3s ease;
    }

    .comment-actions a {
        color: #0073aa;
        font-size: 13px;
        margin-right: 1rem;
        text-decoration: none;
    }

        .comment-actions a:hover {
            color: #005177;
        }

        .comment-actions a.text-warning {
            color: #ffb900;
        }

        .comment-actions a.text-danger {
            color: #d63638;
        }

    .avatar {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        display: block;
    }

    .user-info {
        font-size: 12px;
        color: #888;
        margin-top: 8px;
    }

    .comment-metadata, .comment-response {
        font-size: 12px;
        color: #888;
        text-align: right;
    }

    .filters a {
        color: #0073aa;
        font-weight: bold;
        margin-right: 1rem;
        text-decoration: none;
    }

        .filters a:hover {
            text-decoration: underline;
        }

    .comment-kk {
        scroll-snap-align: start;
        background-color: #fff;
        padding: 3rem 1.5rem;
        border-radius: 1rem;
        box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;
    }

    .text-area-container{
        width: 50%;
        padding: 8px;
        font-size: 14px;
    }

</style>


<body>
    <div class="popular-courses" style="background-color:white">
        <h2 class="courses-title mt-5 px-5">Quản lí bình luận</h2>
        <div class="popular-header px-5">
            <p class="popular-des">Học sáng tạo, thành công vượt trội</p>
        </div>

            <!-- Show Transactions Dropdown -->
        <div class="row mt-4 mb-4 px-5">
            <div class="col-6 d-flex align-items-center">
                <span class="fs-3 me-3">Show</span>
                <select class="drop-show_number" id="pageSize" asp-for="PageSize" options="@Model.PageSize" onchange="submitForm()">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="15">15</option>
                </select>
                <span class="fs-3 ms-3">Comments</span>
            </div>
        </div>

            <!-- Comment Header Row -->
            <div class="row">
                <div class="col-2 table-header text-center">Author</div>
                <div class="col-6 table-header">Comment</div>
                <div class="col-2 table-header text-center">In Course To</div>
                <div class="col-2 table-header text-center">Submitted On</div>
            </div>

            <!-- Comment Item 1 -->
        @foreach ( var comment in Model.PagedComment ) {
            <div class="comment-row">
                <div class="row align-items-center comment-kk mt-2">
                    <div class="col-2 d-flex">
                        <div class="d-flex flex-column ">
                            <img src="@comment.Avatar" alt="Avatar" class="avatar">
                            <div class="user-info">
                                <div>@comment.UserName</div>
                                <div>@comment.UserId</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <p class="mt-1">
                            @((comment.Content.Length > 50) ? @Html.Raw((comment.Content).Substring(0, 50)) + "..." : @Html.Raw(comment.Content))
                        </p>
                        <div class="comment-actions" style="display:flex">
                            <a href="javascript:void(0)" onclick="showReplyArea(@comment.Id)">Reply</a>
                            <a href="javascript:void(0)" onclick="showEditArea(@comment.Id)">Edit</a>
                            <form method="post" asp-page-handler="DeleteComment" asp-route-commentId="@comment.Id">
                                <input type="hidden" name="Id" value="@comment.Id" />
                                <input type="hidden" name="lessonId" value="@comment.LessonId" />
                                    <button class="btn btn-primary" type="submit">Delete</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-2 text-center comment-response">
                        <a asp-page="/Homepage/LearningCourse" asp-route-courseId="@comment.CourseId"
                           asp-route-lessonId="@comment.LessonId">Tới khóa học</a>
                    </div>
                    <div class="col-2 text-center comment-metadata">
                        @comment.CreatedAt.ToString("yyyy/MM/dd")<br>@comment.CreatedAt.ToString("hh:mm tt")
                    </div>
                </div>


                <!-- Reply Text Area -->
                <div id="replyArea-@comment.Id" class="text-area-container" style="display: none;">
                     <form method="post" asp-page-handler="AddReplyComment" >
                        <input type="hidden" name="lessonId" value="@comment.LessonId" />
                     <input type="hidden" name="parentCommentId" value="@comment.Id" />
                     <textarea asp-for="CommentContent" id="default" placeholder="Type your reply here..."></textarea>
                      @Html.ValidationMessageFor(model => model.CommentContent, "", new { @class = "text-danger" })
                    <button onclick="submitReply(@comment.Id)">Submit Reply</button>
                    <button onclick="hideArea('replyArea-@comment.Id')">Cancel</button>
                    </form>
                </div>

                <!-- Edit Text Area -->
                <div id="editArea-@comment.Id" class="text-area-container" style="display: none;">
                    <form method="post" asp-page-handler="EditComment">
                         <input type="hidden" name="lessonId" value="@comment.LessonId" />
                        <input type="hidden" name="Id" value="@comment.Id" />
                        <textarea name="EditedCommentContent" id="default">@comment.Content</textarea>
                    <button data-comment-id="@comment.Id" data-comment-content="@comment.Content" onclick="submitEdit(@comment.Id)">Submit Edit</button>
                    <button onclick="hideArea('editArea-@comment.Id')">Cancel</button>
                    </form>
                </div>
            </div>
        }


        <div class="">
            @*   No <h3>@Model.PageNo</h3>
            Size <h3>@Model.PageSize</h3>
            Total PAGE <h3>@Model.TotalPage</h3> *@
            <ul class="d-flex align-items-center pagination">
                @if ( Model.PageNo > 1 ) {
                    <li class="pagination-btn">
                        <a class="d-block" asp-route-pageNo="@(Model.PagedComment.PageNumber - 1)" asp-route-sortBy="@Model.CurrentSort" asp-route-searchTxt="@Model.CurrentFilter">
                            <i class="fa-solid fa-chevron-left"></i>
                        </a>
                    </li>
                }
                @for ( int i = 1; i <= Model.PagedComment.PageCount; i++ ) {
                    <li class="pagination-btn">
                        <a class="d-block" asp-route-pageNo="@i" asp-route-sortBy="@Model.CurrentSort" asp-route-searchTxt="@Model.CurrentFilter">@i</a>
                    </li>
                }
                @if ( Model.PageNo < Model.TotalPage ) {
                    <li class="pagination-btn">
                        <a class="d-block" asp-route-pageNo="@(Model.PagedComment.PageNumber + 1)" asp-route-sortBy="@Model.CurrentSort" asp-route-searchTxt="@Model.CurrentFilter">
                            <i class="fa-solid fa-chevron-right"></i>
                        </a>
                    </li>
                }
            </ul>
        </div>

        </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="~/tinymce/tinymce.min.js"></script>
    <script src="~/js/tinymceConfig.js"></script>

    <script>
        function showReplyArea(commentId) {
            hideArea(`editArea-${commentId}`);
            document.getElementById(`replyArea-${commentId}`).style.display = 'block';
        }

        function showEditArea(commentId) {
            hideArea(`replyArea-${commentId}`);
            document.getElementById(`editArea-${commentId}`).style.display = 'block';
        }

        function hideArea(areaId) {
            document.getElementById(areaId).style.display = 'none';
        }

        function submitReply(commentId) {
            // Implement reply submission logic here
            alert('Reply submitted for comment ID: ' + commentId);
            hideArea(`replyArea-${commentId}`);
        }

        function submitEdit(commentId) {
            // Implement edit submission logic here
            alert('Edit submitted for comment ID: ' + commentId);
            hideArea(`editArea-${commentId}`);
        }
    </script>


     <script>
        function submitForm() {
            const pageSize = document.getElementById('pageSize').value;
            const sortBy = document.querySelector('input[name="sortBy"]:checked')?.value;
            const searchTxt = document.querySelector('input[name="searchTxt"]').value;
            const queryString = new URLSearchParams({
                pageSize: pageSize,
                sortBy: sortBy || "",
                searchTxt: searchTxt
            }).toString();

            window.location.href = `?${queryString}`;
        }
        let searchBtn = document.getElementById('searchBtn');
        searchBtn.addEventListener('click', () => {
            submitForm()
        });
    </script>


</body>